import Head from 'next/head'
import { Montserrat } from '@next/font/google'
import { Box, Typography } from '@mui/material'
import ListCards from '@/components/ListCards'
import LaunchesCard from '@/components/LaunchesCard'
import useLoadData from '@/Hooks/useLoadData'

const montse = Montserrat({ subsets: ['latin'] })

export default function Home() {
// const [launches, setLaunches] = useState([])
//   const getLunches = async () => {
//       const response = await fetch('/api/getLunches')
//       .then(r => r.json())
//       .then(json => json)      
//       setLaunches(response)
//   }
//   useEffect(() => {
//     getLunches()
//   }, [])

const { data: launches, loading } = useLoadData({ url: '/api/getLunches', options: { limit: 14 } })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montse.className}>        
        <Box sx={{ display: 'flex', justifyContent: 'center', width: '100%' }}>
          <Box sx={{
            flexBasis: '40%',
            display: 'flex',          
            border: '1px solid #eaeaea',
          }}>
            { !loading && <ListCards launches={launches} />}
            { loading && <Typography variant="h4">Loading...</Typography>}
          </Box>          
          <LaunchesCard />          
        </Box>
        </main>  
    </>
  )
}

export async function getStaticProps() {
    const launches = await fetch('http://localhost:3000/api/getLunches')
    .then(r => r.json())
    .then(json => json)    
    return {
        props: {
            launches            
        }
    }
    

}